### PR TITLE
Rearrange and add CI

### PR DESCRIPTION
**Pull request by igitur**
In https://github.com/lukesampson/scoop-extras/pull/4819 @Ash258  recommends that nightly versions be added to this repo.

This PR firstly rearranges (moves .json to bucket/) and adds CI support. I basically copied the functionality from https://github.com/ScoopInstaller/Versions 

Actual CI must still be set up on AppVeyor

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by rasa** [comment]
It appears I don’t have write access to accept this PR.

**Comment by igitur** [comment]
Thanks for merging @rasa

Would you be able to set up the rest if the CI?

**Comment by rasa** [comment]
> Would you be able to set up the rest if the CI?

To be consistent, perhaps GitHub Actions would be a better choice?

**Comment by igitur** [comment]
@rasa Yes, sorry, I wasn't specifically referring to any particular CI implementation. I rather meant whatever is being done on the other repos. In any case, is that something you can set up?

**Pull request merged**
